
BEGIN TRY
	IF OBJECT_ID(N'REL_MagicTitle', N'U') IS NOT NULL
	BEGIN
		SELECT
			0
	END
	ELSE
	BEGIN
		BEGIN TRANSACTION
			CREATE TABLE [dbo].[REL_MagicTitle] (
				[RMT_PK] INT IDENTITY (1, 1) NOT NULL,
				[RMT_Contenuti_Id] INT NOT NULL,
				[RMT_Title] NVARCHAR(1000) NULL,
				[RMT_LangId] NVARCHAR(5) NULL,
				PRIMARY KEY CLUSTERED ([RMT_PK] ASC)
			);
		COMMIT TRANSACTION
		SELECT
			0

	END
END TRY
BEGIN CATCH
	IF XACT_STATE() <> 0
	BEGIN
		ROLLBACK TRANSACTION
	END
	SELECT
		ERROR_NUMBER()
END CATCH;