BEGIN TRY
	IF OBJECT_ID(N'CustomCSS', N'U') IS NOT NULL 
    BEGIN
    	SELECT -1
    END
	ELSE 
	BEGIN
		BEGIN TRANSACTION
			CREATE TABLE [dbo].[CustomCSS] (
				[CSS_PK] INT NOT NULL PRIMARY KEY IDENTITY,
				[CSS_MODIFIED] DATETIME2 NULL DEFAULT GETDATE(),
				[CSS_TEXT] NVARCHAR(MAX) NULL
			)
		COMMIT TRANSACTION
		SELECT 0  	
    END
END TRY
BEGIN CATCH
	IF XACT_STATE() <> 0
	BEGIN
		ROLLBACK TRANSACTION
	END
	SELECT ERROR_NUMBER()
END CATCH;